### PR TITLE
Changes to content to new-year christmas and diwali pages

### LINKED ISSUE #85: New Year page

### PR DESCRIPTION
**Pull request by KarMiles**
## PR contains:
- Add text and images to new-year.html #85
- Remove INFO placeholders from christmas.html

## Breaking changes
- new-year.html
- christmas.html

## Screenshots
 'None'

### CODE REVIEW

**Review by DaveyJH — CHANGES_REQUESTED** [review]
Cannot approve this. christmas.html has a lot more content on the current branch

**Review by mateuszniechwiej — APPROVED** [review]
There is some conflict. It's better to resolve it and then commit new changes

**Review by mateuszniechwiej — DISMISSED** [review]
Maybe better Karol pull from main origin then merge changes

**Review by DaveyJH — CHANGES_REQUESTED** [review]
Please do not merge this. Christmas and Diwali have a lot more content on the main. Please pull from the main and scrap your christmas/diwali changes, New Year is good :+1:

**Review by DaveyJH — APPROVED** [review]

**Pull request merged**
